module.exports = {
  content: ["./**/*.html"],
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        'brand-red': '#ff0057',
        'brand-blue': '#0b2245',
        'brand-yellow': '#ffce00',
        'brand-gray': '#cfcfd1',
      },
      fontFamily: {
        'sans': [
          'Inter',
          'system-ui',
          'BlinkMacSystemFont',
          '-apple-system',
          'Segoe UI',
          'Roboto',
          'Oxygen',
          'Ubuntu',
          'Cantarell',
          'Fira Sans',
          'Droid Sans',
          'Helvetica Neue',
          'sans-serif',
        ],
        'display': [
          'Bebas Neue',
          'Inter',
          'system-ui',
          'BlinkMacSystemFont',
          '-apple-system',
          'Segoe UI',
          'Roboto',
          'Oxygen',
          'Ubuntu',
          'Cantarell',
          'Fira Sans',
          'Droid Sans',
          'Helvetica Neue',
          'sans-serif',
        ],
      },
    },
  },
  variants: {},
  plugins: [require("@tailwindcss/typography")],
};
