backend:
  name: git-gateway
  branch: main
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: false
# local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Content"
    name: "content"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "navigation"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Groups
            name: groups
            widget: list
            allow_add: false
            collapsed: true
            fields:
              - label: Name
                name: name
                widget: string
              - label: Links
                name: items
                widget: list
                allow_add: false
                collapsed: true
                fields:
                  - { label: Name, name: name, widget: string }
                  - { label: Text, name: text, widget: string }
                  - { label: URL, name: url, widget: string }
          - label: Nav Links
            name: items
            widget: list
            allow_add: false
            collapsed: true
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Text, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Homepage"
        name: "homepage"
        file: "src/_data/homepage.yaml"
        fields:
          - label: Welcome Message
            name: welcome_message
            widget: string
      - label: "Events"
        name: "events"
        file: "src/_data/events.yaml"
        fields:
          - label: Events
            name: list
            widget: list
            allow_add: true
            collapsed: true
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Date, name: date, widget: date, format: "YYYY-MM-DD" }
              - { label: Time, name: time, widget: string }
              - { label: Location, name: location, widget: string }
              - { label: Maps URL, name: location_url, widget: string }
              - { label: Description, name: description, widget: text }
              - label: Links
                name: links
                widget: list
                allow_add: true
                collapsed: false
                fields:
                  - { label: Title, name: title, widget: string }
                  - { label: URL, name: url, widget: string }
      - label: "Announcements"
        name: "announcements"
        file: "src/_data/announcements.yaml"
        fields:
          - label: Announcements
            name: items
            widget: list
            allow_add: true
            collapsed: true
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: text }
              - { label: Date, name: date, widget: date, format: "YYYY-MM-DD" }
              - { label: Author, name: author, widget: string }
              - { label: Category, name: category, widget: string }
      - label: "Yard Sale"
        name: "yardsale"
        file: "src/_data/yardsale.yaml"
        fields:
            - { label: Content, name: content, widget: text }
            - { label: Google Form Link, name: google_form, widget: string }
  - label: "Who We Are"
    name: "who_we_are"
    editor:
      preview: false
    files:
      - label: "About PHNA"
        name: "about"
        file: "src/_data/about.yaml"
        fields:
          - { label: About PHNA, name: content, widget: text }
      - label: "History"
        name: "history"
        file: "src/_data/history.yaml"
        fields:
          - { label: History, name: content, widget: text }
      - label: "Mission"
        name: "mission"
        file: "src/_data/mission.yaml"
        fields:
          - { label: Mission, name: mission, widget: text }
      - label: "Board"
        name: "board"
        file: "src/_data/board.yaml"
        fields:
          - { label: Text, name: text, widget: string }
          - label: Members
            name: members
            widget: list
            allow_add: true
            collapsed: true
            fields:
              - { label: Office, name: office, widget: string }
              - { label: Name, name: name, widget: string }
              - { label: Bio, name: bio, widget: text }
              - { label: Email, name: email, widget: string, required: false }
              - { label: Photo, name: photo, widget: image, required: false }
      - label: "Bylaws"
        name: "bylaws"
        file: "src/_data/bylaws.yaml"
        fields:
          - { label: Bylaws URL, name: embed_url, widget: string }
          - label: Minutes
            name: minutes
            widget: object
            fields:
              - { label: Content, name: content, widget: text }
              - { label: URL, name: url, widget: string }
  - label: "Community"
    name: "community"
    editor:
      preview: false
    files:
      - label: "Businesses"
        name: "businesses"
        file: "src/_data/businesses.yaml"
        fields:
          - label: Message
            name: message
            widget: string
          - label: Businesses
            name: items
            widget: list
            allow_add: true
            collapsed: true
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Address Line One, name: address_one, widget: string }
              - { label: Address Line Two, name: address_two, widget: string }
              - { label: Website, name: website, widget: string }
              - { label: Phone, name: phone, widget: string }
              - { label: Image, name: image, widget: image }
      - label: "Helpful Info"
        name: "info"
        file: "src/_data/helpful_info.yaml"
        fields:
          - label: Message
            name: message
            widget: string
          - label: Items
            name: items
            widget: list
            allow_add: true
            collapsed: true
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Website, name: website, widget: string }
              - { label: Phone, name: phone, widget: string }
      - label: "Contact Info"
        name: "contact"
        file: "src/_data/contact_info.yaml"
        fields:
          - label: Message
            name: message
            widget: string
          - label: Items
            name: items
            widget: list
            allow_add: true
            collapsed: true
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Email, name: email, widget: string }
              - { label: Phone, name: phone, widget: string }
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Header"
        name: "header"
        file: "src/_data/header.yaml"
        fields:
          - { label: Header Image, name: image, widget: image, required: true }
      - label: "Site Metadata"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
      - label: "Footer"
        name: "footer"
        file: "src/_data/footer.yaml"
        fields:
          - { label: Email, name: email, widget: string }
          - { label: Facebook, name: facebook, widget: string }
          - { label: Instagram, name: instagram, widget: string }
          - { label: Year, name: year, widget: string }
